





version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_service
    ports:
      - "8002:8080"
    expose:
      - "8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_service
    ports:
      - "80:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


